database:
  host: localhost
  port: 3306
  database: region
  user: root
  password: passwd
  useSsl: false
  properties:
    connectionTimeout: 60000
    idleTimeout: 10000
    maxLifetime: 1800000
    maximumPoolSize: 10
    minimumIdle: 10
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048

regions:
  default-state: WHITELIST # EVERYONE, WHITELIST, NONE